### PR TITLE
refactor(nest): add support for nest cli

### PR DESCRIPTION
**Pull request by yharaskrik**

### CODE REVIEW

**Review by wesleygrimes — DISMISSED** [review]

**Comment by wesleygrimes** [comment]
@santoshyadavdev can you review?

**Review by santoshyadavdev — DISMISSED** [review]
LGTM, there are some lint errors.

**Comment by yharaskrik** [comment]
linting issue fixed and rebased onto master.

**Comment by yharaskrik** [comment]
Checks are all good!

**Review by DominikPieper — DISMISSED** [review]

**Review by DominikPieper — APPROVED** [review]

**Pull request merged**
